packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/eslint-config": ^6.3.1
  "@alanscodelog/semantic-release-config": ^6.0.0
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.2
  "@commitlint/cli": ^20.1.0
  "@iconify/json": ^2.2.393
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.1.3
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.1.3
  "@nuxt/test-utils": ^3.19.2
  "@oslojs/crypto": ^1.0.1
  "@oslojs/encoding": ^1.1.0
  "@tailwindcss/cli": ^4.1.14
  "@types/jsonwebtoken": ^9.0.10
  "@vueuse/core": ^13.9.0
  "@witchcraft/nuxt-logger": ^0.0.9
  "@witchcraft/nuxt-postgres": ^0.3.4
  "@witchcraft/nuxt-utils": ^0.3.6
  "@witchcraft/ui": ^0.3.7
  arctic: ^3.7.0
  changelogen: ^0.6.2
  cookie-es: ^2.0.0
  cross-env: ^10.1.0
  defu: ^6.1.4
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.6
  electron: ^38.2.2
  eslint: ^9.37.0
  h3: 1.15.4
  husky: ^9.1.7
  jsonwebtoken: ^9.0.2
  ms: ^2.1.3
  nuxt: ^4.2.1
  nuxt-security: ^2.4.0
  reka-ui: ^2.5.1
  tailwindcss: ^4.1.14
  tsx: ^4.20.5
  typescript: ^5.9.3
  unplugin-icons: ^22.4.2
  unplugin-vue-components: ^29.1.0
  vitest: ^3.2.4
  vue-tsc: ^3.1.1
  zod: ^4.1.12
